INSERT INTO public."Selecciones"("ID", "Seleccion")VALUES ( ' 1 ',' Francia ');
INSERT INTO public."Selecciones"("ID", "Seleccion")VALUES ( ' 2 ',' Argentina ');
INSERT INTO public."Selecciones"("ID", "Seleccion")VALUES ( ' 3 ',' Costa Rica ');
INSERT INTO public."Selecciones"("ID", "Seleccion")VALUES ( ' 4 ',' Inglaterra ');
INSERT INTO public."Selecciones"("ID", "Seleccion")VALUES ( ' 5 ',' España ');
INSERT INTO public."Selecciones"("ID", "Seleccion")VALUES ( ' 6 ',' Italia ');
INSERT INTO public."Selecciones"("ID", "Seleccion")VALUES ( ' 7 ',' Brazil ');
INSERT INTO public."Selecciones"("ID", "Seleccion")VALUES ( ' 8 ',' Colombia ');

--------------------------------------
INSERT INTO public."Clubes"("ID", "Club")VALUES ( ' 1 ',' Saprissa ');
INSERT INTO public."Clubes"("ID", "Club")VALUES ( ' 2 ',' Heredia ');
INSERT INTO public."Clubes"("ID", "Club")VALUES ( ' 3 ',' Cartago ');
INSERT INTO public."Clubes"("ID", "Club")VALUES ( ' 4 ',' Alajuela ');

-----------------------------------------

INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 1 ',' Francia ',' Hugo ',' Lloris ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 2 ',' Francia ',' Alban ',' Lafont ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 3 ',' Francia ',' Bnenjamin ',' Pavard ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 4 ',' Francia ',' William  ',' Saliba ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 5 ',' Francia ',' Raphael ',' Varane ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 6 ',' Francia ',' Dayot  ',' Upamecano ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 7 ',' Francia ',' Jules ',' Kounde ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 8 ',' Francia ',' Eduardo ',' Camavinga ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 9 ',' Francia ',' Antoine ',' Griezmann ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 10 ',' Francia ',' Aurelien  ',' Tchouameni ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 11 ',' Francia ',' Oliver ',' Giroud ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 12 ',' Francia ',' Kylian ',' Mbappe ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 13 ',' Francia ',' Ousmane ',' Dembele ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 14 ',' Francia ',' Christopher ',' Nkunku ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 15 ',' Francia ',' Matteo ',' Guendouzi ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 16 ',' Francia ',' Jonathan ',' Clauss ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 17 ',' Francia ',' Steve ',' Miranda ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 18 ',' Francia ',' Jordan ',' Veretout ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 19 ',' Francia ',' Ferland ',' Mendy ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 20 ',' Francia ',' Alphonse ',' Areola ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 21 ',' Argentina ',' Franco ',' Armani ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 22 ',' Argentina ',' Lisandro ',' Martinez ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 23 ',' Argentina ',' Nicolas ',' Tagliafico ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 24 ',' Argentina ',' Gonzalo ',' Montiel ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 25 ',' Argentina ',' Leandro ',' Paredes ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 26 ',' Argentina ',' German ',' Pezzella ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 27 ',' Argentina ',' Rodirgo ',' De Paul ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 28 ',' Argentina ',' Thiago ',' Almanda ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 29 ',' Argentina ',' Julian  ',' Alvarez ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 30 ',' Argentina ',' Lionel ',' Messi ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 31 ',' Argentina ',' Angel ',' Di Maria ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 32 ',' Argentina ',' Gerinimo ',' Rulli ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 33 ',' Argentina ',' Cristian ',' Romero ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 34 ',' Argentina ',' Nehuen ',' Perez ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 35 ',' Argentina ',' Angel ',' Correa ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 36 ',' Argentina ',' Papu ',' Gomez ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 37 ',' Argentina ',' Joaquin ',' Correa ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 38 ',' Argentina ',' Giovani ',' Lo Celso ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 39 ',' Argentina ',' Lautaro ',' Martinez ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 40 ',' Argentina ',' Emiliano ',' Martinez ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 41 ',' Costa Rica ',' Keylor ',' Navas ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 42 ',' Costa Rica ',' Joel ',' Campbell ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 43 ',' Costa Rica ',' Brayan ',' Ruiz ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 44 ',' Costa Rica ',' Orlando ',' Galo ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 45 ',' Costa Rica ',' Celso ',' Borges ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 46 ',' Costa Rica ',' Anthony ',' Contreras ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 47 ',' Costa Rica ',' Francisco ',' Calvo ',' Quesada ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 48 ',' Costa Rica ',' Oscar ',' Duarte ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 49 ',' Costa Rica ',' Esteban ',' Alvarado ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 50 ',' Costa Rica ',' Patrick ',' Sequeira ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 51 ',' Costa Rica ',' Juan Pablo ',' Vargas ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 52 ',' Costa Rica ',' Brayan ',' Oviedo ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 53 ',' Costa Rica ',' Brandon ',' Aguilera ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 54 ',' Costa Rica ',' Randall ',' Leal ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 55 ',' Costa Rica ',' Kendall ',' Waston ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 56 ',' Costa Rica ',' Ronald ',' Matarrita ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 57 ',' Costa Rica ',' Cristian ',' Gamboa ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 58 ',' Costa Rica ',' Johan  ',' Venegas ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 59 ',' Costa Rica ',' Yelsin ',' Tejeda ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 60 ',' Costa Rica ',' Giancarlo ',' Gonzalez ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 61 ',' Inglaterra ',' Jordan ',' Pickford ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 62 ',' Inglaterra ',' Harry ',' Kane ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 63 ',' Inglaterra ',' Bukayo ',' Saka ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 64 ',' Inglaterra ',' Harry ',' Maguire ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 65 ',' Inglaterra ',' Jack ',' Grealish ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 66 ',' Inglaterra ',' Phil ',' Foden ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 67 ',' Inglaterra ',' Mason ',' Mount ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 68 ',' Inglaterra ',' Trent ',' Alexander ',' Arnold ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 69 ',' Inglaterra ',' Jude ',' Bellingham ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 70 ',' Inglaterra ',' Raheem ',' Sterling ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 71 ',' Inglaterra ',' Marcus ',' Rashford ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 72 ',' Inglaterra ',' Reece ',' Jame ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 73 ',' Inglaterra ',' Nick  ',' Pope ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 74 ',' Inglaterra ',' Jadon ',' Sancho ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 75 ',' Inglaterra ',' Declan ',' Rice ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 76 ',' Inglaterra ',' Kyle ',' Walker ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 77 ',' Inglaterra ',' Fikayo ',' Tomori ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 78 ',' Inglaterra ',' Luke ',' Shaw ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 79 ',' Inglaterra ',' John ',' Stones ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 80 ',' Inglaterra ',' Eric ',' Dier ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 81 ',' España ',' David ',' De Gea ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 82 ',' España ',' Sergio ',' Ramos ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 83 ',' España ',' Sergio ',' Busquets ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 84 ',' España ',' Adama ',' Traore ',' Diarra ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 85 ',' España ',' Ansu ',' Fati ','     ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 86 ',' España ',' Ferran ',' Torres ','     ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 87 ',' España ',' Alvaro ',' Morata ','     ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 88 ',' España ',' Gavi ',' Paez ','     ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 89 ',' España ',' Pedri ',' Gonzalez ','     ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 90 ',' España ',' Unai ',' Simon ','     ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 91 ',' España ',' Thiago ',' Alcantara ','     ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 92 ',' España ',' Marco ',' Asencio ','     ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 93 ',' España ',' Marc ',' Cucurella ','     ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 94 ',' España ',' Pablo ',' Sarabia ','     ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 95 ',' España ',' Aymeric ',' Laporte ','     ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 96 ',' España ',' Marcos ',' Alonso ',' Mendoza ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 97 ',' España ',' Pau ',' Torres ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 98 ',' España ',' David ',' Raya ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 99 ',' España ',' Dani ',' Olmo ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 100 ',' España ',' Jordi ',' Alba ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 101 ',' Italia ',' Gianluigi ',' Donnarumma ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 102 ',' Italia ',' Ciro ',' Immobile ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 103 ',' Italia ',' Sandro ',' Tonali ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 104 ',' Italia ',' Federico ',' Gatti ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 105 ',' Italia ',' Giovanni ',' Di Lorenzo ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 106 ',' Italia ',' Federico ',' Dimarco ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 107 ',' Italia ',' Rafael ',' Toloi ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 108 ',' Italia ',' Luiz ',' Felipe ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 109 ',' Italia ',' Jorginho ',' Frello ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 110 ',' Italia ',' Gianluca ',' Scamacca ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 111 ',' Italia ',' Giacomo ',' Raspadori ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 112 ',' Italia ',' Wilfried ',' Gnonto ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 113 ',' Italia ',' Alex ',' Meret ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 114 ',' Italia ',' Francesco ',' Acercbi ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 115 ',' Italia ',' Bryan ',' Cristante ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 116 ',' Italia ',' Nicolo ',' Barella ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 117 ',' Italia ',' Leonardo ',' Bonucci ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 118 ',' Italia ',' Alessandro ',' Bastoni ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 119 ',' Italia ',' Ivan ',' Provedel ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 120 ',' Italia ',' Alessio ',' Zerbin ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 121 ',' Brazil ',' Alisson ',' Becker ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 122 ',' Brazil ',' Neymar ',' Jr ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 123 ',' Brazil ',' Richarlison ',' De ',' Andrade ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 124 ',' Brazil ',' Raphinha ',' Dias ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 125 ',' Brazil ',' Vinicius ',' Junior ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 126 ',' Brazil ',' Antony ',' Dos Santos ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 127 ',' Brazil ',' Gabriel ',' Jesus ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 128 ',' Brazil ',' Lucas ',' Paqueta ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 129 ',' Brazil ',' Thiago ',' Silva ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 130 ',' Brazil ',' Carlos ',' Casemiro ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 131 ',' Brazil ',' Dani ',' Alves ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 132 ',' Brazil ',' Rodrygo ',' De Goes ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 133 ',' Brazil ',' Alex ',' Telles ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 134 ',' Brazil ',' Gabriel ',' Barbosa ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 135 ',' Brazil ',' Roberto ',' Firmino ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 136 ',' Brazil ',' Ederson ',' Moraes ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 137 ',' Brazil ',' Matheus ',' Cunha ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 138 ',' Brazil ',' Eder ',' Militao ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 139 ',' Brazil ',' Danilo ',' Da Silva ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 140 ',' Brazil ',' Renan ',' Lodi ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 141 ',' Colombia ',' David ',' Ospina ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 142 ',' Colombia ',' James ',' Rodriguez ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 143 ',' Colombia ',' Luiz ',' Diaz ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 144 ',' Colombia ',' Radamel ',' Falcao ',' Garcia ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 145 ',' Colombia ',' Andres ',' Linas ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 146 ',' Colombia ',' Yaser ',' Asprilla ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 147 ',' Colombia ',' Jorde ',' Carrascal ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 148 ',' Colombia ',' Juan  ',' Cuadrado ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 149 ',' Colombia ',' Yerry ',' Mina ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 150 ',' Colombia ',' Wilmar ',' Barrios ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 151 ',' Colombia ',' Santiago ',' Arias ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 152 ',' Colombia ',' John ',' Duran ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 153 ',' Colombia ',' Roger ',' Martinez ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 154 ',' Colombia ',' John ',' Arias ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 155 ',' Colombia ',' Davinson ',' Sanchez ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 156 ',' Colombia ',' Camilo ',' Vargas ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 157 ',' Colombia ',' Luis ',' Muriel ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 158 ',' Colombia ',' Javier ',' Suarez ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 159 ',' Colombia ',' Duvan ',' Zapata ','    ');
INSERT INTO public."Jugadores_Seleccion"( "ID", "Seleccion", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 160 ',' Colombia ',' Stefan ',' Medina ','    ');

-----------------------------------------------

INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 1 ',' Saprissa ',' Kevin ',' Chamorro ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 2 ',' Saprissa ',' Aron ',' Cruz ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 3 ',' Saprissa ',' Ricardo ',' Blanco ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 4 ',' Saprissa ',' Ryan ',' Bolaños ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 5 ',' Saprissa ',' Kendall ',' Waston ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 6 ',' Saprissa ',' Sergio ',' Cespedes ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 7 ',' Saprissa ',' Walter ',' Cortes ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 8 ',' Saprissa ',' Aubrey ',' David ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 9 ',' Saprissa ',' Kevin ',' Espinoza ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 10 ',' Saprissa ',' Jordy ',' Evans ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 11 ',' Saprissa ',' Marvin ',' Angulo ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 12 ',' Saprissa ',' David ',' Guzman ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 13 ',' Saprissa ',' Jaylon ',' Hadden ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 14 ',' Saprissa ',' Jimmy ',' Marin ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 15 ',' Saprissa ',' Victor ',' Medina ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 16 ',' Saprissa ',' Ulises ',' Segura ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 17 ',' Saprissa ',' Mariano ',' Torres ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 18 ',' Saprissa ',' Alvaro ',' Zamora ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 19 ',' Saprissa ',' Christian ',' Bolaños ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 20 ',' Saprissa ',' Ariel ',' Rodriguez ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 21 ',' Heredia ',' Esteban ',' Alvarado ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 22 ',' Heredia ',' Brayan ',' Segura ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 23 ',' Heredia ',' Orlando ',' Galo ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 24 ',' Heredia ',' Jafet ',' Rodriguez ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 25 ',' Heredia ',' Ariel ',' Soto ',' Gonzalez ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 26 ',' Heredia ',' Douglas ',' Lopez ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 27 ',' Heredia ',' Keysher ',' Fuller ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 28 ',' Heredia ',' Waylon ',' Francis ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 29 ',' Heredia ',' Aaron ',' Salazar ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 30 ',' Heredia ',' Geovanni ',' Campos ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 31 ',' Heredia ',' Gerson ',' Torres ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 32 ',' Heredia ',' Diego ',' Gonzalez ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 33 ',' Heredia ',' Yelsin ',' Tejeda ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 34 ',' Heredia ',' Jefferson ',' Brenes ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 35 ',' Heredia ',' Yendrick ',' Ruiz ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 36 ',' Heredia ',' Kenneth ',' Vargas ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 37 ',' Heredia ',' Brayan ',' Rojas ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 38 ',' Heredia ',' Marcos ',' Escoe ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 39 ',' Heredia ',' Anthony ',' Ruiz ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 40 ',' Heredia ',' Kennedy ',' Rocha ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 41 ',' Cartago ',' Darryl ',' Parker ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 42 ',' Cartago ',' William ',' Quiros ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 43 ',' Cartago ',' Jose ',' Vargas ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 44 ',' Cartago ',' Jeikel ',' Venegas ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 45 ',' Cartago ',' Allen ',' Guevara ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 46 ',' Cartago ',' Mauricio ',' Montero ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 47 ',' Cartago ',' Marcel ',' Hernandez ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 48 ',' Cartago ',' Ronaldo ',' Araya ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 49 ',' Cartago ',' Kenneth ',' Cerdas ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 50 ',' Cartago ',' Marcos ',' Cubillo ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 51 ',' Cartago ',' Byron ',' Bonilla ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 52 ',' Cartago ',' Daniel ',' Chacon ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 53 ',' Cartago ',' Carlos ',' Barahona ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 54 ',' Cartago ',' Marcos ',' Ureña ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 55 ',' Cartago ',' Brandon ',' Bonilla ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 56 ',' Cartago ',' Michael ',' Barrantes ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 57 ',' Cartago ',' Kevin ',' Briceño ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 58 ',' Cartago ',' Dylan ',' Flores ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 59 ',' Cartago ',' Isaac ',' Paris ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 60 ',' Cartago ',' Victor ',' Murillo ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 61 ',' Alajuela ',' Erick ',' Cabalceta ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 62 ',' Alajuela ',' Ian ',' Smith ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 63 ',' Alajuela ',' Celso ',' Borges ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 64 ',' Alajuela ',' Johan ',' Venegas ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 65 ',' Alajuela ',' Brayan ',' Ruiz ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 66 ',' Alajuela ',' Alexander ',' Lopez ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 67 ',' Alajuela ',' Alexis ',' Gamboa ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 68 ',' Alajuela ',' Yael ',' Lopez ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 69 ',' Alajuela ',' Carlos ',' Mora ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 70 ',' Alajuela ',' Giancarlo ',' Gonzalez ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 71 ',' Alajuela ',' Leonel ',' Moreira ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 72 ',' Alajuela ',' Bernald ',' Alfaro ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 73 ',' Alajuela ',' Ian ',' Lawrence ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 74 ',' Alajuela ',' Jose Miguel  ',' Cubero ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 75 ',' Alajuela ',' Miguel ',' Aju ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 76 ',' Alajuela ',' Freddy ',' Gondola ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 77 ',' Alajuela ',' Bayron ',' Mora ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 78 ',' Alajuela ',' Bryan ',' Felix ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 79 ',' Alajuela ',' Aaron ',' Suarez ','    ');
INSERT INTO public."Jugadores_Club"("ID", "Club", "Nombre_Jugador", "Apellido1_Jugador", "Apellido2_Jugador")VALUES ( ' 80 ',' Alajuela ',' Doryan ',' Rodriguez ','    ');
